{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "from pathlib import Path\n",
    "\n",
    "target_directory = '/mounts/data/proj/ayyoob/align_induction/europarl/'\n",
    "\n",
    "text_dir = target_directory+\"text/\"\n",
    "alignments_dir = target_directory+\"alignments/\"\n",
    "download_dir = target_directory+\"downloads/\"\n",
    "\n",
    "Path(text_dir).mkdir(parents=True, exist_ok=True)\n",
    "Path(alignments_dir).mkdir(parents=True, exist_ok=True)\n",
    "Path(download_dir).mkdir(parents=True, exist_ok=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "import urllib.request\n",
    "import shutil\n",
    "import gzip\n",
    "import shutil\n",
    "import zipfile\n",
    "\n",
    "def download_file(url, out_file):\n",
    "# Download the file from `url` and save it locally under `file_name`:\n",
    "    with urllib.request.urlopen(url) as response, open(out_file, 'wb') as out_file:\n",
    "        shutil.copyfileobj(response, out_file)\n",
    "\n",
    "def gzip_extract(in_file, out_file):\n",
    "    with gzip.open(in_file, 'rb') as f_in:\n",
    "        with open(out_file, 'wb') as f_out:\n",
    "            shutil.copyfileobj(f_in, f_out)\n",
    "\n",
    "def zip_extract(in_file, out_directory):\n",
    "    with zipfile.ZipFile(in_file, 'r') as zip_ref:\n",
    "        zip_ref.extractall(out_directory)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/bg.zip\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/bg-cs.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/bg-da.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/bg-de.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/bg-el.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/bg-en.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/bg-es.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/bg-et.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/bg-fi.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/bg-fr.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/bg-hu.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/bg-it.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/bg-lt.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/bg-lv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/bg-nl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/bg-pl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/bg-pt.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/bg-ro.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/bg-sk.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/bg-sl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/bg-sv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/cs.zip\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/cs-da.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/cs-de.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/cs-el.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/cs-en.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/cs-es.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/cs-et.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/cs-fi.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/cs-fr.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/cs-hu.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/cs-it.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/cs-lt.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/cs-lv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/cs-nl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/cs-pl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/cs-pt.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/cs-ro.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/cs-sk.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/cs-sl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/cs-sv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/da.zip\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/da-de.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/da-el.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/da-en.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/da-es.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/da-et.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/da-fi.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/da-fr.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/da-hu.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/da-it.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/da-lt.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/da-lv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/da-nl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/da-pl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/da-pt.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/da-ro.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/da-sk.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/da-sl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/da-sv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/de.zip\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/de-el.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/de-en.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/de-es.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/de-et.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/de-fi.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/de-fr.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/de-hu.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/de-it.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/de-lt.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/de-lv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/de-nl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/de-pl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/de-pt.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/de-ro.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/de-sk.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/de-sl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/de-sv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/el.zip\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/el-en.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/el-es.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/el-et.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/el-fi.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/el-fr.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/el-hu.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/el-it.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/el-lt.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/el-lv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/el-nl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/el-pl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/el-pt.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/el-ro.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/el-sk.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/el-sl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/el-sv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/en.zip\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/en-es.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/en-et.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/en-fi.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/en-fr.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/en-hu.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/en-it.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/en-lt.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/en-lv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/en-nl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/en-pl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/en-pt.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/en-ro.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/en-sk.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/en-sl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/en-sv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/es.zip\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/es-et.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/es-fi.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/es-fr.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/es-hu.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/es-it.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/es-lt.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/es-lv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/es-nl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/es-pl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/es-pt.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/es-ro.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/es-sk.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/es-sl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/es-sv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/et.zip\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/et-fi.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/et-fr.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/et-hu.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/et-it.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/et-lt.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/et-lv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/et-nl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/et-pl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/et-pt.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/et-ro.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/et-sk.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/et-sl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/et-sv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/fi.zip\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/fi-fr.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/fi-hu.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/fi-it.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/fi-lt.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/fi-lv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/fi-nl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/fi-pl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/fi-pt.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/fi-ro.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/fi-sk.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/fi-sl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/fi-sv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/fr.zip\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/fr-hu.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/fr-it.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/fr-lt.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/fr-lv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/fr-nl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/fr-pl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/fr-pt.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/fr-ro.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/fr-sk.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/fr-sl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/fr-sv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/hu.zip\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/hu-it.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/hu-lt.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/hu-lv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/hu-nl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/hu-pl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/hu-pt.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/hu-ro.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/hu-sk.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/hu-sl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/hu-sv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/it.zip\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/it-lt.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/it-lv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/it-nl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/it-pl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/it-pt.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/it-ro.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/it-sk.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/it-sl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/it-sv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/lt.zip\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/lt-lv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/lt-nl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/lt-pl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/lt-pt.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/lt-ro.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/lt-sk.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/lt-sl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/lt-sv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/lv.zip\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/lv-nl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/lv-pl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/lv-pt.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/lv-ro.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/lv-sk.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/lv-sl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/lv-sv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/nl.zip\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/nl-pl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/nl-pt.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/nl-ro.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/nl-sk.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/nl-sl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/nl-sv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/pl.zip\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/pl-pt.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/pl-ro.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/pl-sk.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/pl-sl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/pl-sv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/pt.zip\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/pt-ro.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/pt-sk.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/pt-sl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/pt-sv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/ro.zip\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/ro-sk.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/ro-sl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/ro-sv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/sk.zip\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/sk-sl.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/sk-sv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/sl.zip\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/sl-sv.xml.gz\n",
      "downloading https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/sv.zip\n"
     ]
    }
   ],
   "source": [
    "import urllib.request\n",
    "\n",
    "languages = \"bg cs da de el en es et fi fr hu it lt lv nl pl pt ro sk sl sv\".split()\n",
    "\n",
    "base_link = \"https://opus.nlpl.eu/download.php?f=Europarl/v8/xml/\"\n",
    "\n",
    "\n",
    "for i,lang1 in enumerate(languages):\n",
    "    print('downloading', base_link+lang1+\".zip\")\n",
    "    download_file(base_link+lang1+\".zip\", f\"{download_dir}{lang1}.zip\")\n",
    "    zip_extract(f\"{download_dir}{lang1}.zip\", text_dir)\n",
    "\n",
    "    for lang2 in languages[i+1:]:\n",
    "        print('downloading', f\"{base_link}{lang1}-{lang2}.xml.gz\")\n",
    "        download_file(f\"{base_link}{lang1}-{lang2}.xml.gz\", f\"{download_dir}{lang1}-{lang2}.xml.gz\")\n",
    "        gzip_extract(f\"{download_dir}{lang1}-{lang2}.xml.gz\", f\"{alignments_dir}{lang1}-{lang2}.xml\")\n"
   ]
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "aab640873abb67ad450730b814c8d7de015aa287a6fc3bae4b7154b533e57676"
  },
  "kernelspec": {
   "display_name": "Python 3.7.10 64-bit ('multalign_graph': conda)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.10"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
